### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by CarlosNunezMX** [UnSleepDevs/enigma-cpp#2]
Here some task to finish this project
## Big tasks
- [ ] **Parse JSON config**
   - [ ] **Create a template config file** 
   - [ ] **Finish abstract rotors functionality**
- [ ] **Create a Good Terminal UI** I think @AdorianSAK could do a good work on it!
- [ ] **Make sure all functionality works good on Windows and Linux**
- [ ] **Finish data traitment
## Small Tasks
- [ ] **Add help message**
- [ ] **Create a worker in Github for autocompiling**

**Comment by CarlosNunezMX** [comment]
I am going to work on Worker related task :smile:

**Comment by CarlosNunezMX** [comment]
Working on task, Create a template configuration file, commit: d22d8837711a9fa6efdf866721ed50c757c55b7b
